module.exports = {
  'Elektronika': 'electronics gadgets tech product flat lay',
  'Moda damska': 'women fashion clothing apparel catalog',
  'Moda męska': 'men fashion clothing apparel catalog',
  'Dom i ogród': 'home and garden decor interior',
  'Sport': 'sports equipment gear minimal product',
  'Zabawki': 'toys kids colorful studio product',
  'Motoryzacja': 'automotive car parts detail studio',
  'Książki': 'books stack reading minimal',
  'Zdrowie i uroda': 'cosmetics skincare beauty product',
  'Kultura i rozrywka': 'entertainment music movie tickets',
  'AGD': 'home appliances kitchen appliance product',
  'Meble': 'furniture modern living room',
  'Biuro i szkoła': 'stationery office school supplies flat lay',
  'Telefony': 'smartphone mobile phone product',
  'Komputery': 'computer laptop pc setup desk',
  'Foto i wideo': 'camera photography gear product',
  'Dziecko': 'baby products pastel minimal',
  'Supermarket': 'groceries food flat lay',
  'Obuwie': 'shoes sneakers product studio',
  'Torby i plecaki': 'bags backpacks product studio',
  'Bielizna': 'underwear socks folded product no model',
  'Ozdoby': 'jewelry accessories product macro',
  'Narzędzia': 'tools hardware workshop flat lay',
  'Ogród': 'garden tools plants',
  'Kuchnia': 'kitchen utensils cookware product',
  'Łazienka': 'bathroom accessories towels minimal',
  'Gry': 'video games console controller',
  'Rowery': 'bicycle bike gear studio',
  'Fitness': 'fitness equipment gym dumbbells',
  'Turystyka': 'travel gear backpack map flat lay',
};
